name: Tests

on:
    push:
        branches-ignore:
            - master
        tags:
            - v*

jobs:
    build:
        name: Build with PHP ${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php: [ 8.0, 8.1, 8.2 ]
                dependency-version: [ prefer-stable ]
                os: [ ubuntu-latest ]

        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
                if: success()

            - name: setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1.6'

            - name: install dependencies
              if: success()
              run: |
                  php -v
                  composer install --no-interaction
                  zip -qr http-client-build.zip ./ -x '*.git*'

            - name: build artifact
              uses: actions/upload-artifact@v2
              with:
                  name: http-client-build.zip
                  path: http-client-build.zip

    test:
        timeout-minutes: 10
        needs: [build]
        name: Test with PHP ${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php: [ 8.0, 8.1, 8.2 ]
                dependency-version: [ prefer-stable ]
                os: [ ubuntu-latest ]

        steps:
            - name: download artifact
              uses: actions/download-artifact@v2
              with:
                  name: http-client-build.zip
                  path: ./

            - name: "prepare package"
              if: success()
              run: |
                  unzip -q http-client-build.zip

            - name: "run PHPUnit"
              if: success() && github.event.pull_request.draft == false
              run: |
                  composer test

    styles:
        timeout-minutes: 10
        needs: [ build ]
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php: [8.0]
                dependency-version: [ prefer-stable ]
                os: [ ubuntu-latest ]

        steps:
            - name: download artifact
              uses: actions/download-artifact@v2
              with:
                  name: http-client-build.zip
                  path: ./

            - name: "prepare package"
              if: success()
              run: |
                  unzip -q http-client-build.zip

            - name: run & apply fixes
              run: |
                  PHP_CS_FIXER_IGNORE_ENV=1 composer fix-style

            - uses: stefanzweifel/git-auto-commit-action@v4.0.0
              with:
                  commit_message: apply coding style fixes

