name: Build

on:
    push:
        branches-ignore:
            - master
        tags:
            - v*

jobs:
    setup:
        name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php: [ 8.0, 8.1, 8.2 ]
                dependency-version: [ prefer-stable ]
                os: [ ubuntu-latest ]

        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
                if: success()

            - name: Install Dependencies
              if: success()
              run: |
                  php -v
                  composer install --no-interaction
                  zip -qr http-client-build.zip ./ -x '*.git*'

            - name: Build Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: http-client-build.zip
                  path: http-client-build.zip

    tests:
        timeout-minutes: 10
        needs: [setup]
        name: Test with PHP ${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php: [ 8.0, 8.1, 8.2 ]
                dependency-version: [ prefer-stable ]
                os: [ ubuntu-latest ]

        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v2
              with:
                  name: http-client-build.zip
                  path: ./

            - name: Prepare Package
              if: success()
              run: |
                  unzip -q http-client-build.zip

            - name: Run Tests
              if: success() && github.event.pull_request.draft == false
              run: |
                  composer test

    styles:
        timeout-minutes: 10
        needs: [tests]
        name: Fix Code Styles
        runs-on: ubuntu-latest

        steps:
            - name: Git Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
                if: success()

            - name: Install Dependencies
              run: |
                composer install --no-scripts

            - name: Run & Apply Code Style Fixes
              env:
                  PHP_CS_FIXER_IGNORE_ENV: true
              run: |
                  composer fix-style

            - uses: stefanzweifel/git-auto-commit-action@v4.0.0
              with:
                  commit_message: apply coding style fixes

